Update action.yaml

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -1,16 +1,16 @@
 runs:
-  using: "composite"
-  steps:
-  - name: Run failing
-    run: exit 1
-    continue-on-error: true
-    shell: bash
-  - name: Uses failing
-    uses: nikola-jokic/failing-composite@main
-    continue-on-error: true
-  - name: Echo OK
-    run: echo 'OK'
-    shell: bash
+#   using: "composite"
+#   steps:
+#   - name: Run failing
+#     run: exit 1
+#     continue-on-error: true
+#     shell: bash
+#   - name: Uses failing
+#     uses: nikola-jokic/failing-composite@main
+#     continue-on-error: true
+#   - name: Echo OK
+#     run: echo 'OK'
+#     shell: bash
   
   
   
@@ -22,14 +22,14 @@ runs:
 #       echo ${{github.event_path}}
 #       echo ${{github.workspace}}
         
-#   using: "composite"
-#   defaults:
-#     run:
-#       #shell: bash
-#       working-directory: custom
-#   steps:
-#     - run: pwd
-#     - run: ./shell.sh
-#     - run: echo "bla bla 1"
-#     - run: echo "bla bla 2"
-#     - run: echo "bla bla 3"
+  using: "composite"
+  defaults:
+    run:
+      #shell: bash
+      working-directory: custom
+  steps:
+    - run: pwd
+    - run: ./shell.sh
+    - run: echo "bla bla 1"
+    - run: echo "bla bla 2"
+    - run: echo "bla bla 3"
